oe_whitelabel.settings:
  type: theme_settings
  label: 'OE Whitelabel settings'
  mapping:
    component_library:
      type: string
      label: 'BCL component library, either EC, EU or neutral'
    header_style:
      type: string
      label: 'Header style, either Blue header or Light header'
