oe_whitelabel.settings:
  type: oe_bootstrap_theme.settings
  label: 'OE Whitelabel settings'
  mapping:
    component_library:
      type: string
      label: 'BCL component library, either EC, EU or neutral'
    header_style:
      type: string
      label: 'Header style, either Blue header or Light header'
    slim_select:
      type: mapping
      label: 'Slim select settings'
      mapping:
        all_select_elements:
          type: boolean
          label: 'Slim select for all select elements'
