<?php

/**
 * @file
 * OE Whitelabel Paragraphs module.
 *
 * Preprocess hooks are implemented on behalf of the oe_whitelabel theme.
 * This prevents hooks from running if oe_whitelabel is not the active theme.
 *
 * phpcs:disable Drupal.NamingConventions.ValidFunctionName.InvalidPrefix
 */

declare(strict_types=1);

use Drupal\oe_bootstrap_theme\ConfigImporter;
use Drupal\oe_whitelabel\ColorSchemePreprocess;

/**
 * Implements hook_modules_installed().
 */
function oe_whitelabel_paragraphs_modules_installed($modules, $is_syncing) {
  if ($is_syncing) {
    return;
  }

  // Import the gallery paragraph view display override when the related
  // module is installed.
  if (in_array('oe_paragraphs_gallery', $modules)) {
    ConfigImporter::importSingle('module', 'oe_whitelabel_paragraphs', '/config/overrides/', 'core.entity_view_display.paragraph.oe_gallery.default');
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Adds a bare, markup-free template suggestion to all paragraph fields.
 */
function oe_whitelabel_paragraphs_theme_suggestions_field_alter(array &$suggestions, array $variables): void {
  $element = $variables['element'];

  // Do not output field labels and wrapping markup for paragraph fields.
  if (isset($element['#entity_type']) && $element['#entity_type'] === 'paragraph') {
    // Prepend the new suggestion to the list. This will put it right after the
    // default field template. By doing this we allow to override single
    // fields, while keeping all the rest markup-free.
    array_unshift($suggestions, 'field__bare');
  }
}

/**
 * Implements hook_preprocess_HOOK() for gallery paragraph.
 */
function oe_whitelabel_paragraphs_preprocess_paragraph__oe_gallery(&$variables) {
  // Since the gallery paragraph has a description field, we cannot use the
  // title of the gallery pattern. To allow the flexibility of changing the
  // title tag, we set it up here so that further preprocess hooks can change
  // it.
  $variables['title_tag'] = 'h2';
}

/**
 * Implements hook_preprocess_paragraph() for oe_document paragraph.
 */
function oe_whitelabel_paragraphs_preprocess_paragraph__oe_document(array &$variables): void {
  /** @var \Drupal\oe_whitelabel\ColorSchemePreprocess $color_scheme_preprocess */
  $color_scheme_preprocess = \Drupal::classResolver(ColorSchemePreprocess::class);
  $color_scheme_preprocess->injectColorScheme($variables, [
    'text_colored' => TRUE,
  ]);
}

/**
 * Implements hook_preprocess_paragraph() for oe_quote paragraph.
 */
function oe_whitelabel_paragraphs_preprocess_paragraph__oe_quote(array &$variables): void {
  /** @var \Drupal\oe_whitelabel\ColorSchemePreprocess $color_scheme_preprocess */
  $color_scheme_preprocess = \Drupal::classResolver(ColorSchemePreprocess::class);
  $color_scheme_preprocess->injectColorScheme($variables, [
    'background' => 'default',
    'text_colored' => TRUE,
  ]);
}
