<?php

declare(strict_types=1);

namespace Drupal\oe_whitelabel_helper\Plugin\field_group\FieldGroupFormatter;

use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Theme\ComponentPluginManager;
use Drupal\field_group\FieldGroupFormatterBase;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Base class for field group formatters that use a pattern for rendering.
 *
 * Field group formatters extending this class generate a pattern context that
 * is compatible with the one generated by the ui_patterns_field_group module.
 *
 * If you need to override pattern templates based on node, bundle or view mode
 * just enable the ui_patterns_field_group module.
 *
 * @see https://ui-patterns.readthedocs.io/en/8.x-1.x/content/developer-documentation.html#working-with-pattern-suggestions
 */
abstract class PatternFormatterBase extends FieldGroupFormatterBase implements ContainerFactoryPluginInterface {

  /**
   * Component plugin manager.
   */
  protected ComponentPluginManager $componentManager;

  /**
   * PatternFormatterBase constructor.
   *
   * @param array $configuration
   *   A configuration array containing information about the plugin instance.
   * @param string $plugin_id
   *   The plugin_id for the plugin instance.
   * @param array $plugin_definition
   *   The plugin implementation definition.
   * @param \Drupal\Core\Theme\ComponentPluginManager $component_manager
   *   Component plugin manager.
   */
  public function __construct(array $configuration, string $plugin_id, array $plugin_definition, ComponentPluginManager $component_manager) {
    parent::__construct($plugin_id, $plugin_definition, $configuration['group'], $configuration['settings'], $configuration['label']);
    $this->configuration = $configuration;
    $this->componentManager = $component_manager;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('plugin.manager.sdc')
    );
  }

  /**
   * {@inheritdoc}
   */
  public static function defaultSettings() {
    return [
      'label' => '',
      'variant' => '',
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function settingsForm() {
    $definition = $this->componentManager->getDefinition($this->getComponentId());

    $form['label'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Field group label'),
      '#default_value' => $this->label,
    ];

    $variants = $definition['variants'] ?? [];
    if (!empty($variants)) {
      $options = [];
      foreach ($variants as $variant_id => $variant) {
        $options[$variant_id] = $variant['title'] ?? $variant_id;
      }
      $form['variant'] = [
        '#title' => $this->t('Variant'),
        '#type' => 'select',
        '#options' => $options,
        '#default_value' => $this->getSetting('variant'),
      ];
    }

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function settingsSummary() {
    $summary = [];

    if ($this->getLabel()) {
      $summary[] = $this->t('Label: @label', ['@label' => $this->getLabel()]);
    }

    if ($this->getSetting('variant')) {
      $summary[] = $this->t('Variant: @variant', ['@variant' => $this->getSetting('variant')]);
    }

    return $summary;
  }

  /**
   * {@inheritdoc}
   */
  public function preRender(&$element, $rendering_object) {
    parent::preRender($element, $rendering_object);

    $props = $this->getFields($element, $rendering_object);
    if ($props === NULL) {
      // Don't render the component.
      return;
    }
    $pattern = [
      '#type' => 'component',
      '#component' => $this->getComponentId(),
      '#variant' => $this->getSetting('variant'),
      '#props' => $props,
      '#context' => [
        'type' => 'field_group',
        'group_name' => $element['#group_name'],
        'entity_type' => $element['#entity_type'],
        'bundle' => $element['#bundle'],
        'view_mode' => $this->group->mode,
      ],
    ];

    // Remove all renderable elements, while keeping render metadata as that can
    // be used to further manipulate the render array.
    foreach (Element::children($element) as $key) {
      unset($element[$key]);
    }
    $element += [
      'pattern' => $pattern,
    ];
  }

  /**
   * Gets the component ID for the current formatter plugin.
   *
   * @return string
   *   Pattern ID.
   */
  protected function getComponentId(): string {
    return 'oe_bootstrap_theme:' . $this->getPatternId();
  }

  /**
   * Return pattern ID for the current formatter plugin.
   *
   * @return string
   *   Pattern ID.
   */
  abstract protected function getPatternId(): string;

  /**
   * Return list of fields for the current pattern.
   *
   * @param array $element
   *   Field group render element.
   * @param object $rendering_object
   *   Field group rendering object.
   *
   * @return array|null
   *   Pattern fields to be rendered, or NULL if the field group
   *   should not be displayed at all.
   */
  abstract protected function getFields(array &$element, $rendering_object): ?array;

}
