<?php

declare(strict_types=1);

namespace Drupal\oe_whitelabel_helper\Plugin\field_group\FieldGroupFormatter;

use Drupal\Core\Plugin\ContainerFactoryPluginInterface;
use Drupal\ui_patterns\UiPatternsManager;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Newer base class for field group formatters that use a pattern for rendering.
 *
 * This can be used instead of the older PatternFormatterBase.
 * It provides a more orthodox emptiness detection, and a slightly different
 * API.
 *
 * Field group formatters extending this class generate a pattern context that
 * is compatible with the one generated by the ui_patterns_field_group module.
 *
 * If you need to override pattern templates based on node, bundle or view mode
 * just enable the ui_patterns_field_group module.
 *
 * @see https://ui-patterns.readthedocs.io/en/8.x-1.x/content/developer-documentation.html#working-with-pattern-suggestions
 * @see \Drupal\oe_whitelabel_helper\Plugin\field_group\FieldGroupFormatter\PatternFormatterBase
 */
abstract class PreRenderingPatternFormatterBase extends PreRenderingFieldGroupFormatterBase implements ContainerFactoryPluginInterface {

  /**
   * PatternFormatterBase constructor.
   *
   * @param array $configuration
   *   A configuration array containing information about the plugin instance.
   * @param string $plugin_id
   *   The plugin_id for the plugin instance.
   * @param array $plugin_definition
   *   The plugin implementation definition.
   * @param \Drupal\ui_patterns\UiPatternsManager $patternsManager
   *   UI Patterns manager.
   */
  public function __construct(
    array $configuration,
    string $plugin_id,
    array $plugin_definition,
    protected readonly UiPatternsManager $patternsManager,
  ) {
    parent::__construct(
      $plugin_id,
      $plugin_definition,
      $configuration['group'],
      $configuration['settings'],
      $configuration['label'],
    );
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('plugin.manager.ui_patterns')
    );
  }

  /**
   * {@inheritdoc}
   */
  public static function defaultSettings() {
    // @todo Support settings from the parent class?
    return [
      'label' => '',
      'variant' => '',
    ];
  }

  /**
   * {@inheritdoc}
   */
  public function settingsForm() {
    // @todo Support settings from the parent class?
    $pattern = $this->patternsManager->getDefinition($this->getPatternId());

    $form['label'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Field group label'),
      '#default_value' => $this->label,
    ];

    if ($pattern->hasVariants()) {
      $form['variant'] = [
        '#title' => $this->t('Variant'),
        '#type' => 'select',
        '#options' => $pattern->getVariantsAsOptions(),
        '#default_value' => $this->getSetting('variant'),
      ];
    }

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function settingsSummary() {
    $summary = [];

    if ($this->getLabel()) {
      $summary[] = $this->t('Label: @label', ['@label' => $this->getLabel()]);
    }

    if ($this->getSetting('variant')) {
      $summary[] = $this->t('Variant: @variant', ['@variant' => $this->getSetting('variant')]);
    }

    return $summary;
  }

  /**
   * Builds a pattern render element.
   *
   * This is meant to be called by sub-classes.
   */
  protected function buildPatternElement(array $fields): array {
    // Instantiate the pattern render array.
    return [
      '#type' => 'pattern',
      '#id' => $this->getPatternId(),
      '#variant' => $this->getSetting('variant'),
      '#fields' => $fields,
      '#context' => [
        'type' => 'field_group',
        'group_name' => $this->group->group_name,
        'entity_type' => $this->group->entity_type,
        'bundle' => $this->group->bundle,
        'view_mode' => $this->group->mode,
      ],
    ];
  }

  /**
   * Return pattern ID for the current formatter plugin.
   *
   * This is a separate method, to make sure that the same pattern id is used in
   * the settings form and in the display.
   *
   * @return string
   *   Pattern ID.
   */
  abstract protected function getPatternId(): string;

}
