block.settings.whitelabel_search_block:
  type: block_settings
  label: OE Whitelabel search block
  mapping:
    form:
      type: mapping
      label: Form
      mapping:
        action:
          type: string
          label: Action
        layout:
          type: string
          label: Region
    view_options:
      type: mapping
      label: View Options
      mapping:
        enable_autocomplete:
          type: boolean
          label: Enable autocomplete
        id:
          type: string
          label: View id
        display:
          type: string
          label: View display
