block.settings.whitelabel_search_block:
  type: block_settings
  label: OE Whitelabel search block
  mapping:
    region:
      type: string
      label: region
    view_options:
      type: mapping
      label: View Options
      mapping:
        enable_autocomplete:
          type: boolean
          label: Enable autocomplete
        id:
          type: string
          label: View id
        display:
          type: string
          label: View display
