field.formatter.settings.oe_whitelabel_helper_address_inline:
  type: mapping
  label: 'Address inline formatter settings'
  mapping:
    delimiter:
      type: string
      label: 'Delimiter for address items.'
condition.plugin.oe_whitelabel_helper_current_component_library:
  type: condition.plugin
  mapping:
    component_library:
      type: string
field_group.field_group_formatter_plugin.oe_whitelabel_helper_pattern_base:
  type: field_group.field_group_formatter_plugin.base
  label: 'Mapping for the base pattern formatter settings'
  mapping:
    label:
      type: label
      label: 'Field group label'
    variant:
      type: string
      label: 'Pattern variant'
field_group.field_group_formatter_plugin.oe_whitelabel_helper_description_list_pattern:
  type: field_group.field_group_formatter_plugin.oe_whitelabel_helper_pattern_base
  label: 'Mapping for the description list pattern formatter settings'

field.formatter.settings.oe_whitelabel_helper_gallery:
  type: mapping
  label: 'Gallery formatter settings'

field.formatter.third_party.oe_whitelabel_helper:
  type: mapping
  label: 'OpenEuropa Whitelabel Helper third party setting'
  mapping:
    gallery_formatter:
      type: string
      label: 'To which gallery item property the field is mapped.'
