<?php

/**
 * @file
 * OE Whitelabel Search Module.
 */

declare(strict_types =  1);

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for facets_forms.
 */
function oe_whitelabel_search_form_facets_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  if (isset($form['actions'])) {
    $action_classes = ['mt-4', 'd-grid', 'gap-4', 'd-md-block'];
    if (!isset($form['actions']['#attributes']['class'])) {
      $form['actions']['#attributes']['class'] = [];
    }
    $form['actions']['#attributes']['class'] = array_merge($form['actions']['#attributes']['class'], $action_classes);
  }
  if (isset($form['actions']['submit'])) {
    $submit_classes = ['me-md-3', 'btn', 'btn-primary', 'btn-md'];
    if (!isset($form['actions']['submit']['#attributes']['class'])) {
      $form['actions']['submit']['#attributes']['class'] = [];
    }
    $form['actions']['submit']['#attributes']['class'] = array_merge($form['actions']['submit']['#attributes']['class'], $submit_classes);
  }
  if (isset($form['actions']['reset'])) {
    $reset_classes = ['btn', 'btn-light', 'btn-md'];
    if (!isset($form['actions']['reset']['#attributes']['class'])) {
      $form['actions']['reset']['#attributes']['class'] = [];
    }
    $form['actions']['reset']['#attributes']['class'] = array_merge($form['actions']['reset']['#attributes']['class'], $reset_classes);
  }
}

/**
 * Implements hook_preprocess_HOOK() for facet_summary_item_list.
 */
function oe_whitelabel_search_preprocess_facets_summary_item_list(array &$variables): void {
  $items = [];
  foreach ($variables['items'] as $item) {
    if ($item['value']['#type'] === 'link') {
      $item['value']['#attributes']['class'] = 'standalone';
      $items[] = $item;
    }
  }
  $variables['items'] = $items;
}

use Drupal\block\Entity\Block;

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_whitelabel_search_preprocess_block(&$variables) {
  if ($variables['plugin_id'] === 'whitelabel_search_block') {
    $block = Block::load($variables['elements']['#id']);
    $variables['content']['#region'] = $block->getRegion();
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function oe_whitelabel_search_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (!empty($variables['element']['#form_id'])) {
    $suggestions[] = 'form__' . $variables['element']['#region'];
    $suggestions[] = 'form__' . $variables['element']['#region'] . '__' . $variables['element']['#form_id'];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function oe_whitelabel_search_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
  if (empty($variables['element']['#form_id'])) {
    return;
  }

  $suggestions[] = 'form_element__' . $variables['element']['#form_id'];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function oe_whitelabel_search_theme_suggestions_input_alter(array &$suggestions, array $variables) {

  if ($variables['element']['#form_id'] !== 'oe_whitelabel_search_form') {
    return;
  }

  $suggestions[] = 'input__textfield__' . $variables['element']['#region'] . '__' . $variables['element']['#form_id'];
}
